# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-sc'
    repository: 'ashorg/delash'
    command: 'buildAndPush'
    Dockerfile: 'delash-prj1/Dockerfile'
    buildContext: '$(Build.Repository.LocalPath)'
    tags: 'v$(Build.BuildId)'

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: '2.13.1'

- task: HelmDeploy@0
  inputs:
    command: 'package'
    chartPath: 'charts/asp'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

